"""
Difficulty level words
"""
easy_words = ['area', 'army', 'away', 'baby', 'back', 'ball', 'band', 'bank',
              'base', 'bath', 'bear', 'beat', 'been', 'beer', 'bell', 'belt',
              'best', 'bill', 'bird', 'blow', 'blue', 'boat', 'body', 'bomb',
              'bond', 'bone', 'book', 'boom', 'born', 'boss', 'both', 'bowl',
              'bulk', 'burn', 'bush', 'busy', 'call', 'calm', 'came', 'camp',
              'card', 'care', 'case', 'cash', 'cast', 'cell', 'chat', 'chip',
              'city', 'club', 'coal', 'coat', 'code', 'cold', 'come', 'cook',
              'cool', 'cope', 'copy', 'cost', 'crew', 'crop', 'dark', 'data',
              'date', 'dawn', 'days', 'dead', 'deal', 'dean', 'dear', 'debt',
              'deep', 'deny', 'desk', 'dial', 'diet', 'disc', 'disk', 'does',
              'done', 'door', 'dose', 'down', 'draw', 'drew', 'drop', 'drug',
              'dual', 'duke', 'dust', 'duty', 'each', 'earn', 'ease', 'east',
              'easy', 'edge', 'even', 'ever', 'evil', 'exit', 'face', 'fact',
              'fail', 'fair', 'fall', 'farm', 'fast', 'fate', 'fear', 'feed',
              'feel', 'feet', 'fell', 'felt', 'file', 'fill', 'film', 'find',
              'fine', 'fire', 'firm', 'fish', 'five', 'flat', 'flow', 'food',
              'foot', 'ford', 'form', 'fort', 'four', 'free', 'fuel', 'full',
              'fund', 'gain', 'game', 'gate', 'gave', 'gear', 'gene', 'gift',
              'girl', 'give', 'glad', 'goal', 'goes', 'gold', 'gone', 'good',
              'gray', 'grew', 'grey', 'grow', 'gulf', 'hair', 'half', 'hall',
              'hand', 'hang', 'hard', 'harm', 'hate', 'have', 'head', 'hear',
              'heat', 'held', 'hell', 'help', 'here', 'hero', 'high', 'hill',
              'hire', 'hold', 'hole', 'holy', 'home', 'hope', 'host', 'hour',
              'huge', 'hung', 'hunt', 'hurt', 'idea', 'inch', 'into', 'iron',
              'item', 'jack', 'jane', 'jean', 'john', 'join', 'jump', 'jury',
              'just', 'keen', 'keep', 'kent', 'kept', 'kick', 'kill', 'kind',
              'king', 'knee', 'knew', 'know', 'lack', 'lady', 'laid', 'lake',
              'land', 'lane', 'last', 'late', 'lead', 'left', 'less', 'life',
              'lift', 'like', 'line', 'link', 'list', 'live', 'load', 'loan',
              'lock', 'logo', 'long', 'look', 'lord', 'lose', 'loss', 'lost',
              'love', 'luck', 'made', 'mail', 'main', 'make', 'male', 'many',
              'mass', 'matt', 'meal', 'mean', 'meat', 'meet', 'menu', 'mere',
              'mike', 'mile', 'milk', 'mill', 'mind', 'mine', 'miss', 'mode',
              'mood', 'moon', 'more', 'most', 'move', 'much', 'must', 'name',
              'navy', 'near', 'neck', 'need', 'news', 'next', 'nice', 'nick',
              'nine', 'none', 'nose', 'note', 'okay', 'once', 'only', 'onto',
              'open', 'oral', 'over', 'pace', 'pack', 'page', 'paid', 'pain',
              'pair', 'palm', 'park', 'part', 'past', 'path', 'peak', 'pick',
              'pink', 'pipe', 'plan', 'play', 'plot', 'plug', 'plus', 'poll',
              'pool', 'poor', 'port', 'post', 'pull', 'pure', 'push', 'race',
              'rail', 'rain', 'rank', 'rare', 'rate', 'read', 'real', 'rear',
              'rely', 'rent', 'rest', 'rice', 'rich', 'ride', 'ring', 'rise',
              'risk', 'road', 'rock', 'role', 'roll', 'roof', 'room', 'root',
              'rose', 'rule', 'rush', 'ruth', 'safe', 'said', 'sake', 'sale',
              'salt', 'same', 'sand', 'save', 'seat', 'seed', 'seek', 'seem',
              'seen', 'sell', 'send', 'sent', 'sept', 'ship', 'shop', 'shot',
              'show', 'shut', 'sick', 'side', 'sign', 'site', 'size', 'skin',
              'slip', 'slow', 'snow', 'soft', 'soil', 'sold', 'sole', 'some',
              'song', 'soon', 'sort', 'soul', 'spot', 'star', 'stay', 'step',
              'stop', 'such', 'suit', 'sure', 'take', 'tale', 'talk', 'tall',
              'tank', 'tape', 'task', 'team', 'tech', 'tell', 'tend', 'term',
              'test', 'text', 'than', 'that', 'them', 'then', 'they', 'thin',
              'this', 'thus', 'till', 'time', 'tiny', 'told', 'toll', 'tone',
              'tony', 'took', 'tool', 'tour', 'town', 'tree', 'trip', 'true',
              'tune', 'turn', 'twin', 'type', 'unit', 'upon', 'used', 'user',
              'vary', 'vast', 'very', 'vice', 'view', 'vote', 'wage', 'wait',
              'wake', 'walk', 'wall', 'want', 'ward', 'warm', 'wash', 'wave',
              'ways', 'weak', 'wear', 'week', 'well', 'went', 'were', 'west',
              'what', 'when', 'whom', 'wide', 'wife', 'wild', 'will', 'wind',
              'wine', 'wing', 'wire', 'wise', 'wish', 'wood', 'word', 'wore',
              'work', 'yard', 'yeah', 'year', 'your', 'zero', 'zone']

med_words = ['yellow', 'carbon', 'career', 'castle', 'casual', 'caught',
             'center', 'centre', 'chance', 'change', 'charge', 'choice',
             'choose', 'chosen', 'church', 'circle', 'client', 'closed',
             'closer', 'coffee', 'column', 'combat', 'coming', 'common',
             'comply', 'copper', 'corner', 'costly', 'county', 'couple',
             'course', 'covers', 'create', 'credit', 'crisis', 'custom',
             'damage', 'danger', 'dealer', 'debate', 'decade', 'decide',
             'defeat', 'defend', 'define', 'degree', 'demand', 'depend',
             'deputy', 'desert', 'design', 'desire', 'detail', 'detect',
             'device', 'differ', 'dinner', 'direct', 'doctor', 'dollar',
             'domain', 'double', 'driven', 'driver', 'during', 'easily',
             'eating', 'editor', 'effect', 'effort', 'eighth', 'either',
             'eleven', 'emerge', 'empire', 'employ', 'enable', 'ending',
             'energy', 'engage', 'engine', 'enough', 'ensure', 'entire',
             'entity', 'equity', 'escape', 'estate', 'ethnic', 'exceed',
             'except', 'excess', 'expand', 'expect', 'expert', 'export',
             'extend', 'extent', 'fabric', 'facing', 'factor', 'failed',
             'fairly', 'fallen', 'family', 'famous', 'father', 'fellow',
             'female', 'figure', 'filing', 'finger', 'finish', 'fiscal',
             'flight', 'flying', 'follow', 'forced', 'forest', 'forget',
             'formal', 'format', 'former', 'foster', 'fought', 'fourth',
             'friend', 'future', 'garden', 'gather', 'gender', 'german',
             'global', 'golden', 'ground', 'growth', 'guilty', 'handed',
             'handle', 'happen', 'hardly', 'headed', 'health', 'height',
             'hidden', 'holder', 'honest', 'impact', 'import', 'income',
             'indeed', 'injury', 'inside', 'intend', 'intent', 'invest',
             'island', 'itself', 'jersey', 'joseph', 'junior', 'killed',
             'labour', 'latest', 'latter', 'launch', 'lawyer', 'leader',
             'league', 'leaves', 'legacy', 'length', 'lesson', 'letter',
             'lights', 'likely', 'linked', 'liquid', 'listen', 'little',
             'living', 'losing', 'lucent', 'luxury', 'mainly', 'making',
             'manage', 'manner', 'manual', 'margin', 'marine', 'marked',
             'market', 'martin', 'master', 'matter', 'mature', 'medium',
             'member', 'memory', 'mental', 'merely', 'merger', 'method',
             'middle', 'miller', 'mining', 'minute', 'mirror', 'mobile',
             'modern', 'modest', 'module', 'moment', 'morris', 'mostly',
             'mother', 'motion', 'moving', 'murder', 'museum', 'mutual',
             'myself', 'narrow', 'nation', 'native', 'nature', 'nearby',
             'nearly', 'nights', 'nobody', 'normal', 'notice', 'notion',
             'number', 'object', 'obtain', 'office', 'offset', 'online',
             'option', 'orange', 'origin', 'output', 'oxford', 'packed',
             'palace', 'parent', 'partly', 'patent', 'people', 'period',
             'permit', 'person', 'phrase', 'picked', 'planet', 'player',
             'please', 'plenty', 'pocket', 'police', 'policy', 'prefer',
             'pretty', 'prince', 'prison', 'profit', 'proper', 'proven',
             'public', 'pursue', 'raised', 'random', 'rarely', 'rather',
             'rating', 'reader', 'really', 'reason', 'recall', 'recent',
             'record', 'reduce', 'reform', 'regard', 'regime', 'region',
             'relate', 'relief', 'remain', 'remote', 'remove', 'repair',
             'repeat', 'replay', 'report', 'rescue', 'resort', 'result',
             'retail', 'retain', 'return', 'reveal', 'review', 'reward',
             'riding', 'rising', 'robust', 'ruling', 'safety', 'salary',
             'sample', 'saving', 'saying', 'scheme', 'school', 'screen',
             'search', 'season', 'second', 'secret', 'sector', 'secure',
             'seeing', 'select', 'seller', 'senior', 'series', 'server',
             'settle', 'severe', 'sexual', 'should', 'signal', 'signed',
             'silent', 'silver', 'simple', 'simply', 'single', 'sister',
             'slight', 'smooth', 'social', 'solely', 'sought', 'source',
             'soviet', 'speech', 'spirit', 'spoken', 'spread', 'spring',
             'square', 'stable', 'status', 'steady', 'stolen', 'strain',
             'stream', 'street', 'stress', 'strict', 'strike', 'string',
             'strong', 'struck', 'studio', 'submit', 'sudden', 'suffer',
             'summer', 'summit', 'supply', 'surely', 'survey', 'switch',
             'symbol', 'system', 'taking', 'talent', 'target', 'taught',
             'tenant', 'tender', 'tennis', 'thanks', 'theory', 'thirty',
             'though', 'threat', 'thrown', 'ticket', 'timely', 'timing',
             'tissue', 'toward', 'travel', 'treaty', 'trying', 'twelve',
             'twenty', 'unable', 'unique', 'united', 'unless', 'unlike',
             'update', 'useful', 'valley', 'varied', 'vendor', 'versus',
             'victim', 'vision', 'visual', 'volume', 'walker', 'wealth',
             'weekly', 'weight', 'wholly', 'window', 'winner', 'winter',
             'within', 'wonder', 'worker', 'wright', 'writer']

hard_words = ['everything', 'aboveboard', 'Washington', 'basketball',
              'weathering', 'characters', 'literature', 'perfection',
              'volleyball', 'depression', 'homecoming', 'technology',
              'maleficent', 'watermelon', 'appreciate', 'relaxation',
              'convection', 'abominable', 'government', 'salmonella',
              'strawberry', 'aberration', 'retirement', 'television',
              'contraband', 'silhouette', 'friendship', 'loneliness',
              'punishment', 'university', 'Cinderella', 'confidence',
              'restaurant', 'abstinence', 'blancmange', 'blackboard',
              'discipline', 'renovation', 'helicopter', 'generation',
              'adaptation', 'skateboard', 'lightboard', 'understand',
              'wilderness', 'motivation', 'pilgrimage', 'diabolical',
              'kaepernick', 'orthopedic', 'conscience', 'reciprocal',
              'absolution', 'management', 'rainforest', 'girlfriend',
              'trampoline', 'resolution', 'vegetables', 'accountant',
              'expression', 'illuminati', 'earthquake', 'protection',
              'tambourine', 'endearment', 'individual', 'innovation',
              'abstaining', 'gymnastics', 'excitement', 'allocution',
              'elementary', 'conference', 'adrenaline', 'accomplish',
              'instrument', 'ubiquitous', 'accounting', 'speechless',
              'concussion', 'mozzarella', 'compliment', 'appearance',
              'difference', 'accelerate', 'underworld', 'affliction',
              'everywhere', 'bronchitis', 'breathless', 'leadership',
              'revolution', 'insulation', 'alliteration', 'unidentified',
              'intermittent', 'exacerbation', 'independence', 'commensalism',
              'thanksgiving', 'professional', 'organization', 'sporadically',
              'intimidating', 'abolitionist', 'onomatopoeia', 'appreciation',
              'annunciation', 'malnutrition', 'architecture', 'biodiversity',
              'acceleration', 'interdiction', 'trigonometry', 'communicator',
              'bodybuilding', 'perspiration', 'appertaining', 'resurrection',
              'constipation', 'civilization', 'velociraptor', 'retrocession',
              'expectations', 'ambidextrous', 'cytoskeleton', 'hippopotamus',
              'interjection', 'exasperation', 'felicitation', 'abbreviation',
              'voluminosity', 'rambunctious', 'colonization', 'interception',
              'championship', 'acquaintance', 'depreciation', 'consequences',
              'grandparents', 'intelligence', 'relationship']
